## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [2]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [5]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
dfbi = pd.read_csv("bridge-inspections-excerpt.csv")
dfbi

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [23]:
## call the first 10 rows
dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [10]:
## call the last 5 rows
dfbi.tail(=

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [12]:
## call a 20 random rows
dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
36864,48,29,'LEON CREEK',29353658.0,98355477.0,1.0,17.0,1987.0,5,2.0,7,7,7,7,N,NaN
74193,50,15,'LAMOILLE RIVER',44390391.0,72485261.0,3.0,9.0,1887.0,7,12.0,8,6,7,8,N,NaN
40800,48,255,'SAN ANTONIO RIVER',28531498.0,97471198.0,2.0,9.0,1973.0,5,2.0,6,7,4,4,N,NaN
94862,53,51,'DAVIS CREEK',48163027.0,117154951.0,1.0,6.0,1936.0,7,2.0,6,7,5,7,N,NaN
70710,49,49,'UNION PACIFIC RAILROAD',39555301.0,111095962.0,1.0,2.0,1978.0,4,2.0,6,5,6,N,N,1.0
31488,48,321,'COTTONWOOD CREEK',28590474.0,95580336.0,4.0,19.0,1958.0,1,1.0,6,6,2,2,N,NaN
11771,48,359,'US 385',35141336.0,102254046.0,1.0,1.0,1973.0,5,2.0,6,6,6,N,N,NaN
73584,49,35,'SR-68; Redwood Road',40300232.0,111561666.0,NaN,14.0,2015.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
74821,50,25,'HUNTER BROOK',42563402.0,72451464.0,3.0,9.0,1987.0,3,2.0,8,7,8,6,N,NaN
64995,48,453,'BLUE BLUFF RD',30192492.0,97344800.0,NaN,9.0,2007.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
34081,48,453,'COLORADO RIVER',30123253.0,97381793.0,1.0,16.0,2015.0,5,2.0,7,8,8,8,N,NaN
71920,49,41,'SR-118 INTCHG. X-ROAD',38372903.0,112133378.0,1.0,1.0,1985.0,5,2.0,7,7,6,N,N,1.0
46962,48,113,'BACHMAN CREEK',32503715.0,96522296.0,4.0,14.0,1941.0,3,2.0,7,6,6,6,N,NaN
72444,49,47,'HILL CREEK',39434690.0,109435560.0,62.0,9.0,2013.0,1,19.0,N,N,N,5,6,NaN
5800,48,237,'W FORK OF TRINITY RIVER',33244840.0,98220997.0,1.0,6.0,1996.0,5,2.0,7,7,7,7,N,NaN
13192,48,371,'DRAW',30445280.0,101534360.0,1.0,7.0,1932.0,1,19.0,N,N,N,7,6,NaN
35691,48,491,'BATTLEGROUND CREEK',30311875.0,97253783.0,2.0,9.0,1994.0,1,19.0,N,N,N,7,5,NaN
35690,48,491,'BATTLEGROUND CREEK',30305239.0,97250257.0,2.0,9.0,1987.0,1,19.0,N,N,N,6,7,NaN
32852,48,171,'ROGERS DRAW',30180005.0,99145503.0,1.0,2.0,1931.0,1,19.0,N,N,N,7,7,NaN
49988,48,257,'DRAW',32415501.0,96263517.0,1.0,11.0,1987.0,1,19.0,N,N,N,5,6,NaN

In [9]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
df.info()

## there are 99_999 rows, 16 columns with integers, strings and floating numbers (=datatypes)

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

### Which column has the most missing data...just a quick estimate?
column 15, the Pier_Protection_111 column only has 4353 with data

In [13]:
## call the top 7 rows
dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [14]:
## call a sample of 10
dfbi.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
36173,48,491,'BLOCK HOUSE CREEK',30332608.0,97491466.0,32.0,12.0,2007.0,5,2.0,7,7,7,7,N,NaN
92307,51,183,'Route 646',36485860.0,77272132.0,NaN,8.0,1982.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
34226,48,453,'DRAW',30240999.0,97434162.0,1.0,17.0,1989.0,1,19.0,N,N,N,7,7,NaN
49779,48,139,'WAXAHACHIE CREEK TRIB',32185951.0,96441349.0,2.0,9.0,2006.0,5,2.0,7,7,7,6,N,NaN
53369,48,351,'DEMPSEY CREEK',30402526.0,93404268.0,1.0,7.0,1956.0,1,2.0,6,7,6,7,N,NaN
72103,49,27,'COUNTY ROAD',39112045.0,112114922.0,1.0,1.0,1978.0,5,2.0,7,7,6,N,N,1.0
86286,51,550,'IS 464',36482092.0,76164740.0,1.0,17.0,1983.0,4,2.0,7,6,6,N,N,NaN
34574,48,453,'WALLER CREEK',30162095.0,97440756.0,4.0,17.0,1931.0,1,4.0,6,6,6,6,N,NaN
30349,48,149,'Big Fivemile Creek',29415095.0,97061982.0,1.0,1.0,1969.0,1,19.0,N,N,N,7,7,NaN
31694,48,469,'DRAIN',28514529.0,96595849.0,1.0,2.0,2003.0,1,19.0,N,N,N,7,7,NaN

In [16]:
## call the bottom 6
dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [24]:
## call the year built column using dot notation
dfbi.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [25]:
## call FEATURES_DESC_006A as a series using square bracket notation
dfbi["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [31]:
## what are the unique owner codes?
dfbi["OWNER_022"].unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

In [32]:
dfbi["OWNER_022"].nunique()

32

In [ ]:
##In total there a 32 different owner codes in that row that appear at least once.